export const contactControls = [
  { type: "text", label: "First Name", id: "firstName", required: true },
  { type: "text", label: "Last Name", id: "lastName", required: true },
  { type: "email", label: "Email", id: "email", required: true },
  { type: "tel", label: "Phone", id: "phone", required: false },
];

export const educationControls = [
  { type: "text", label: "School", id: "school", required: true },
  { type: "select", label: "Major", id: "major", required: false },
  { type: "date", label: "Graduation", id: "graduation", required: true },
];

export const majors = [
  "Accounting",
  "Advertising",
  "Agriculture",
  "Anthropology",
  "Architecture",
  "Art History",
  "Biology",
  "Biomedical Engineering",
  "Business Administration",
  "Chemistry",
  "Civil Engineering",
  "Communication",
  "Computer Engineering",
  "Computer Science",
  "Criminal Justice",
  "Data Science",
  "Design",
  "Economics",
  "Education",
  "Electrical Engineering",
  "English",
  "Environmental Science",
  "Finance",
  "Graphic Design",
  "Health Sciences",
  "History",
  "Hospitality Management",
  "Human Resources",
  "Industrial Engineering",
  "Information Technology",
  "International Relations",
  "Journalism",
  "Law",
  "Management",
  "Marketing",
  "Mathematics",
  "Mechanical Engineering",
  "Medicine",
  "Music",
  "Nursing",
  "Philosophy",
  "Physics",
  "Political Science",
  "Psychology",
  "Public Health",
  "Sociology",
  "Software Engineering",
  "Theater",
  "Visual Arts",
];
